import type { Metadata } from "next"
import { Geist, Geist_Mono, Erica_One } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const ericaOne = Erica_One({
  variable: "--font-erica-one",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ericaOne.variable} container px-4 mx-auto antialiased`}
      >
        <header className="pt-8 pb-10 mx-auto text-center">
          <h1 className="font-serif text-6xl mb-2">MATCH GAME</h1>
          <button className="font-bold rounded-md bg-yellow-300 py-2 px-4 tracking-wide">
            Instructions
          </button>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
